# Generated by Django 4.1.5 on 2023-02-07 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('MadhyaPradesh, MP', 'Madhyapradesh'), ('Gujarat, Guj', 'Gujarat'), ('UttarPradesh, UP', 'Uttarpradesh'), ('Karnataka, Kar', 'Karnataka')], default='MadhyaPradesh, MP', max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('other', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
    ]
